# ---- Resilience settings ----
JSON_RETRY_WAIT = 300
BAD_JSON_STREAK_LIMIT = 3
INTERNET_POLL_INTERVAL = 5
INTERNET_CHECK_HOST = "8.8.8.8"
INTERNET_CHECK_PORT = 53

NETWORK_ERROR_PATTERNS = [
    "ERR_INTERNET_DISCONNECTED", "ERR_NETWORK_CHANGED", "ERR_CONNECTION_",
    "ERR_NAME_NOT_RESOLVED", "ERR_TIMED_OUT", "ERR_ADDRESS_UNREACHABLE",
    "net::ERR", "NS_ERROR_", "getaddrinfo", "Timeout", "ECONNRESET",
]