"""
card_render.py
---------------
Shared rendering logic for the student-ID-card pipeline.

Both the scraper (card_filler.py) and the browser editor (editor_app.py)
import from here so that the "first draft" produced by the scraper and the
image produced after you edit something in the browser are generated by the
exact same code path (no drift between preview and final export).

Everything about *where things sit on the card* (text position, font size,
colour, the photo box, photo crop/rotation) lives in a JSON-serialisable
"layout" dict. build_default_layout() creates the original hard-coded
layout as a starting point; the editor lets you change any of it and saves
the result back into the record's sidecar JSON file.
"""

import copy
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont

TEMPLATE_PATH = "template.png"
FONT_REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

# Designed templates live in a templates/ folder next to the project root.
# "active_template.json" is the pointer that the normal batch run reads, so a
# design saved with `cardfiller.py --new` is automatically applied afterwards.
TEMPLATES_DIR = Path("templates")
ACTIVE_TEMPLATE_FILE = TEMPLATES_DIR / "active_template.json"

# ---- Original hard-coded defaults (kept as the starting layout) ----
VALUE_COLOR = (208, 0, 0)
NAME_COLOR = (255, 255, 255)
SECTION_COLOR = (222, 255, 0)

FIELD_FONT_SIZE = 44
NAME_FONT_SIZE = 79
SECTION_FONT_SIZE = 54

FIELD_MIN_FONT_SIZE = 18
NAME_MIN_FONT_SIZE = 30

# Positions are EXACTLY the fixedCard.py values. Each (x, y) is a PIL
# *anchor point*, not a top-left corner: fields/section use "lm"
# (left-middle), the name uses "mm" (middle-middle) and the address uses
# "la" (left-ascender). draw_text_box() below replicates fixedCard.py's
# shrink-to-fit logic exactly, so the exported card is pixel-identical to
# the original fixedCard.py output.
FIELD_POSITIONS = {
    "father_name":   (440, 859),
    "mother_name":   (440, 915),
    "dob":           (440, 971),
    "class":         (440, 1027),
    "roll_number":   (440, 1083),
    "mobile_number": (440, 1140),
    "address":       (440, 1177),
}

NAME_CENTER = (531, 784)      # fixedCard.py NAME_CENTER, drawn with anchor "mm"
SECTION_POSITION = (27, 1394) # fixedCard.py SECTION_POSITION, drawn with anchor "lm"

PHOTO_BOX = (371, 292, 319, 431)  # x, y, w, h
PHOTO_CORNER_RADIUS = 20

# fixedCard.py shrink-fit boxes: field width = 1062 - 440 - 30 = 592,
# address height = 1394 - 1177 - 20 = 197, name width = 1062 - 60 = 1002,
# section width = 1062 - 27 - 30 = 1005.
ADDRESS_BOX_WIDTH = 592
ADDRESS_BOX_HEIGHT = 197

_FACE_CASCADE = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")


def rgb_to_hex(rgb):
    return "#%02x%02x%02x" % tuple(rgb)


def hex_to_rgb(h):
    h = (h or "").lstrip("#")
    if len(h) != 6:
        return (0, 0, 0)
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


# ---------------------------------------------------------------- layout ---

def build_default_layout():
    """The original hard-coded positions/sizes/colours, as an editable dict."""
    layout = {
        "photo": {
            "x": PHOTO_BOX[0], "y": PHOTO_BOX[1],
            "width": PHOTO_BOX[2], "height": PHOTO_BOX[3],
            "rotation": 0,
            "corner_radius": PHOTO_CORNER_RADIUS,
            # crop rectangle in the ORIGINAL uploaded image's pixel space.
            # Filled in per-record when the sidecar is first created.
            "crop": None,
        },
        "texts": {
            "student_name": {
                "x": NAME_CENTER[0], "y": NAME_CENTER[1],
                "width": 1002, "anchor": "mm",
                "font_size": NAME_FONT_SIZE, "min_font_size": NAME_MIN_FONT_SIZE,
                "color": rgb_to_hex(NAME_COLOR), "align": "center", "bold": True,
                "uppercase": True,
            },
            "section": {
                "x": SECTION_POSITION[0], "y": SECTION_POSITION[1],
                "width": 1005, "anchor": "lm",
                "font_size": SECTION_FONT_SIZE, "min_font_size": 20,
                "color": rgb_to_hex(SECTION_COLOR), "align": "left", "bold": True,
                "prefix": "Sec- ",
            },
        },
    }
    for key, (x, y) in FIELD_POSITIONS.items():
        if key == "address":
            layout["texts"][key] = {
                "x": x, "y": y, "width": ADDRESS_BOX_WIDTH, "height": ADDRESS_BOX_HEIGHT,
                "anchor": "la",
                "font_size": FIELD_FONT_SIZE, "min_font_size": FIELD_MIN_FONT_SIZE,
                "color": rgb_to_hex(VALUE_COLOR), "align": "left", "bold": True,
                "multiline": True,
            }
        else:
            layout["texts"][key] = {
                "x": x, "y": y, "width": 592, "anchor": "lm",
                "font_size": FIELD_FONT_SIZE, "min_font_size": FIELD_MIN_FONT_SIZE,
                "color": rgb_to_hex(VALUE_COLOR), "align": "left", "bold": True,
            }
    return layout


def merge_layout(default, override):
    """Deep-merge an override layout (possibly partial) onto the default one."""
    result = copy.deepcopy(default)
    if not override:
        return result
    for section in ("photo",):
        if section in override and override[section]:
            result[section].update(override[section])
    if "texts" in override:
        for key, val in override["texts"].items():
            if key in result["texts"]:
                result["texts"][key].update(val)
            else:
                result["texts"][key] = val
    return result


# ------------------------------------------------------------ photo utils ---

_ROTATIONS = [None, cv2.ROTATE_90_CLOCKWISE, cv2.ROTATE_180, cv2.ROTATE_90_COUNTERCLOCKWISE]
ROTATION_CONFIDENCE_MARGIN = 1.4
PHOTO_PAD_SIDE = 0.35
PHOTO_PAD_TOP = 0.45
PHOTO_PAD_BOTTOM = 0.65


def detect_face_crop_rect(image_path: Path, ai_ratios=None):
    """
    Best-effort face detection used only to seed a *starting* crop rectangle
    (in ORIGINAL image pixel coordinates, rotation=0) for the editor. The
    user can freely adjust this afterwards, so it doesn't need to be exact.
    Returns {"x","y","w","h"} or None.
    """
    img = cv2.imread(str(image_path))
    if img is None:
        return None
    h_img, w_img = img.shape[:2]

    if ai_ratios:
        rx = int(ai_ratios[0] * w_img)
        ry = int(ai_ratios[1] * h_img)
        rw = int(ai_ratios[2] * w_img)
        rh = int(ai_ratios[3] * h_img)
        rx, ry = max(0, rx), max(0, ry)
        rw, rh = max(1, min(rw, w_img - rx)), max(1, min(rh, h_img - ry))
    else:
        rx, ry, rw, rh = 0, 0, w_img, h_img

    roi = img[ry:ry + rh, rx:rx + rw]
    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    faces = _FACE_CASCADE.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))
    if len(faces) == 0:
        # no face found: just return the AI region (or whole image) as the starting crop
        return {"x": rx, "y": ry, "w": rw, "h": rh}

    fx, fy, fw, fh = max(faces, key=lambda f: f[2] * f[3])
    pad_side = fw * PHOTO_PAD_SIDE
    pad_top = fh * PHOTO_PAD_TOP
    pad_bottom = fh * PHOTO_PAD_BOTTOM

    x0 = rx + fx - pad_side
    y0 = ry + fy - pad_top
    x1 = rx + fx + fw + pad_side
    y1 = ry + fy + fh + pad_bottom

    x0, y0 = max(0, int(x0)), max(0, int(y0))
    x1, y1 = min(w_img, int(x1)), min(h_img, int(y1))
    return {"x": x0, "y": y0, "w": max(1, x1 - x0), "h": max(1, y1 - y0)}


def enhance_photo(img: Image.Image) -> Image.Image:
    arr = cv2.cvtColor(np.array(img.convert("RGB")), cv2.COLOR_RGB2BGR)
    arr = cv2.resize(arr, None, fx=3, fy=3, interpolation=cv2.INTER_CUBIC)
    arr = cv2.fastNlMeansDenoisingColored(arr, None, 10, 10, 7, 21)

    out = np.zeros_like(arr, np.float32)
    for c in range(3):
        ch = arr[:, :, c].astype(np.float32)
        lo, hi = np.percentile(ch, 0.5), np.percentile(ch, 99.5)
        out[:, :, c] = np.clip((ch - lo) * 255.0 / max(hi - lo, 1), 0, 255)
    arr = out.astype(np.uint8)

    lab = cv2.cvtColor(arr, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    l = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(l)
    arr = cv2.cvtColor(cv2.merge((l, a, b)), cv2.COLOR_LAB2BGR)

    hsv = cv2.cvtColor(arr, cv2.COLOR_BGR2HSV).astype(np.float32)
    hsv[..., 1] = np.clip(hsv[..., 1] * 1.15, 0, 255)
    arr = cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2BGR)

    arr = cv2.bilateralFilter(arr, 9, 75, 75)

    blur = cv2.GaussianBlur(arr, (0, 0), 2.0)
    arr = cv2.addWeighted(arr, 1.5, blur, -0.5, 0)

    return Image.fromarray(cv2.cvtColor(arr, cv2.COLOR_BGR2RGB))


def fit_cover(img: Image.Image, target_w: int, target_h: int) -> Image.Image:
    src_w, src_h = img.size
    scale = max(target_w / src_w, target_h / src_h)
    new_w, new_h = int(src_w * scale + 0.5), int(src_h * scale + 0.5)
    resized = img.resize((new_w, new_h), Image.LANCZOS)
    left = (new_w - target_w) // 2
    top = (new_h - target_h) // 2
    return resized.crop((left, top, left + target_w, top + target_h))


def add_rounded_corners(img: Image.Image, radius: int) -> Image.Image:
    img = img.convert("RGBA")
    mask = Image.new("L", img.size, 0)
    mask_draw = ImageDraw.Draw(mask)
    mask_draw.rounded_rectangle([0, 0, img.size[0] - 1, img.size[1] - 1], radius=radius, fill=255)
    img.putalpha(mask)
    return img


def load_cropped_photo(source_image_path, crop, rotation=0, enhance=True):
    """Open the original image, crop to `crop` (dict x,y,w,h), rotate by
    `rotation` degrees (arbitrary angle, expand canvas), optionally enhance."""
    if not source_image_path or not Path(source_image_path).exists() or not crop:
        return None
    img = Image.open(source_image_path).convert("RGB")
    x, y, w, h = crop["x"], crop["y"], crop["w"], crop["h"]
    x, y = max(0, int(x)), max(0, int(y))
    w, h = max(1, int(w)), max(1, int(h))
    x2, y2 = min(img.width, x + w), min(img.height, y + h)
    cropped = img.crop((x, y, x2, y2))
    if rotation:
        cropped = cropped.rotate(-float(rotation), expand=True, resample=Image.BICUBIC, fillcolor=(255, 255, 255))
    if enhance:
        cropped = enhance_photo(cropped)
    return cropped


# -------------------------------------------------------------- text draw ---

def _wrap_lines(text, font, max_width):
    wrapped = []
    for line in text.split("\n"):
        words = line.split()
        current = ""
        for word in words:
            test = (current + " " + word).strip()
            bbox = font.getbbox(test)
            if bbox[2] - bbox[0] <= max_width or not current:
                current = test
            else:
                wrapped.append(current)
                current = word
        wrapped.append(current)
    return wrapped


def _autofit(draw, text, x, y, max_width, font_path, base_size, color, min_size, anchor):
    """Exact copy of fixedCard.py draw_autofit_text(): single-line, shrink
    by 1pt until it fits max_width, draw with the given PIL anchor."""
    font_size = base_size
    font = ImageFont.truetype(font_path, font_size)
    while font_size > min_size:
        bbox = font.getbbox(text)
        text_width = bbox[2] - bbox[0]
        if text_width <= max_width:
            break
        font_size -= 1
        font = ImageFont.truetype(font_path, font_size)
    draw.text((x, y), text, font=font, fill=color, anchor=anchor)


def _fitted(draw, text, x, y, max_width, max_height, font_path, base_size, color, min_size):
    """Exact copy of fixedCard.py draw_fitted_text(): word-wrap the address,
    shrink by 2pt until it fits max_height, draw with anchor 'la'."""
    def wrap_lines(font):
        lines = text.split("\n")
        wrapped = []
        for line in lines:
            words = line.split()
            current = ""
            for word in words:
                test = (current + " " + word).strip()
                test_bbox = font.getbbox(test)
                if test_bbox[2] - test_bbox[0] <= max_width:
                    current = test
                else:
                    if current:
                        wrapped.append(current)
                    current = word
            if current:
                wrapped.append(current)
        return wrapped

    font_size = base_size
    while font_size > min_size:
        font = ImageFont.truetype(font_path, font_size)
        bbox = font.getbbox("Ay")
        line_height = bbox[3] - bbox[1] + 4
        wrapped = wrap_lines(font)
        total_height = len(wrapped) * line_height
        if total_height <= max_height:
            for i, wline in enumerate(wrapped):
                draw.text((x, y + i * line_height), wline, font=font, fill=color, anchor="la")
            return
        font_size -= 2

    font = ImageFont.truetype(font_path, font_size)
    bbox = font.getbbox("Ay")
    line_height = bbox[3] - bbox[1] + 4
    wrapped = wrap_lines(font)
    for i, wline in enumerate(wrapped):
        draw.text((x, y + i * line_height), wline, font=font, fill=color, anchor="la")


def draw_text_box(draw, text, spec, font_bold=FONT_BOLD, font_regular=FONT_REGULAR):
    """Draw one text field according to its layout spec.

    When the spec carries an 'anchor' it uses fixedCard.py's exact rendering
    (positions are PIL anchor points: lm/mm/la). Specs without an anchor are
    treated as a top-left box (x, y) with text aligned within `width`."""
    if not text:
        return
    x, y = spec["x"], spec["y"]
    color = hex_to_rgb(spec.get("color", "#D00000"))
    font_path = font_bold if spec.get("bold", True) else font_regular
    base_size = spec.get("font_size", FIELD_FONT_SIZE)
    min_size = spec.get("min_font_size", 14)
    width = spec.get("width")
    max_height = spec.get("height")
    multiline = spec.get("multiline", False)
    anchor = spec.get("anchor")

    if anchor:
        if multiline:
            _fitted(draw, text, x, y, width or 500, max_height or 200,
                    font_path, base_size, color, min_size)
        else:
            _autofit(draw, text, x, y, width or 500, font_path, base_size,
                     color, min_size, anchor)
        return

    # ---- legacy top-left-box path (specs saved without an anchor) ----
    align = spec.get("align", "left")

    font_size = base_size
    while font_size > min_size:
        font = ImageFont.truetype(font_path, font_size)
        lines = _wrap_lines(text, font, width) if (multiline or "\n" in text) else [text]
        if not multiline and len(lines) > 1:
            lines = [text]  # single-line fields: don't wrap, just shrink
        bbox = font.getbbox("Ay")
        line_height = bbox[3] - bbox[1] + 6
        total_height = line_height * len(lines)
        fits_height = max_height is None or total_height <= max_height
        fits_width = all(font.getbbox(l)[2] - font.getbbox(l)[0] <= width for l in lines) or multiline
        if fits_height and (fits_width or not multiline):
            break
        font_size -= 2
    else:
        font = ImageFont.truetype(font_path, min_size)
        lines = _wrap_lines(text, font, width) if (multiline or "\n" in text) else [text]
        bbox = font.getbbox("Ay")
        line_height = bbox[3] - bbox[1] + 6

    for i, line in enumerate(lines):
        line_bbox = font.getbbox(line)
        line_w = line_bbox[2] - line_bbox[0]
        if align == "center":
            draw_x = x + (width - line_w) / 2
        elif align == "right":
            draw_x = x + (width - line_w)
        else:
            draw_x = x
        draw.text((draw_x, y + i * line_height), line, font=font, fill=color, anchor="la")


# --------------------------------------------------------- template IO ---

def save_active_template(name: str, layout: dict, dummy_data: dict,
                         template_file: str = "template.png") -> Path:
    """Persist a designed template as the one the next batch run uses.

    `template_file` is the relative path to the template image, `layout` the
    photo-box + text-field configuration, and `dummy_data` the sample values
    used while designing (kept so you can re-open and tweak the design).
    """
    import json

    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    cfg = {
        "name": name,
        "template_file": template_file,
        "layout": layout,
        "dummy_data": dummy_data or {},
    }
    ACTIVE_TEMPLATE_FILE.write_text(
        json.dumps(cfg, ensure_ascii=False, indent=2), encoding="utf-8")
    return ACTIVE_TEMPLATE_FILE


def load_active_template() -> dict | None:
    """Return the saved active-template config ({"name","template_file",
    "layout","dummy_data"}) or None if none has been designed / the template
    image is missing. The layout has the crop applied at fill-time, so this
    just supplies the base positions/styles."""
    import json
    import copy
    if not ACTIVE_TEMPLATE_FILE.exists():
        return None
    try:
        cfg = json.loads(ACTIVE_TEMPLATE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return None
    if not Path(cfg.get("template_file", "")).exists():
        return None
    cfg["layout"] = merge_layout(build_default_layout(), cfg.get("layout"))
    return cfg


def list_designed_templates() -> list[dict]:
    """Metadata for every template stored under templates/ (each has a
    *_template.png and its design JSON), for the --new picker."""
    import json
    items = []
    for p in sorted(TEMPLATES_DIR.glob("*_template.png")):
        stem = p.stem[:-9]  # strip "_template"
        cfg = TEMPLATES_DIR / f"{stem}_design.json"
        items.append({
            "name": stem,
            "template_file": str(p),
            "config_file": str(cfg),
        })
    return items


# ---------------------------------------------------------------- render ---

def render_card(data: dict, layout: dict, template_path=TEMPLATE_PATH, photo_source_path=None):
    """Compose the final card image from `data` (field values) and `layout`
    (positions/styles/photo box+crop). Returns a PIL.Image (RGB)."""
    if not Path(template_path).exists():
        raise FileNotFoundError(f"Template not found at {template_path}")
    im = Image.open(template_path).convert("RGB")
    draw = ImageDraw.Draw(im)

    photo_spec = layout.get("photo", {})
    crop = photo_spec.get("crop")
    if photo_source_path and crop:
        photo = load_cropped_photo(photo_source_path, crop, rotation=photo_spec.get("rotation", 0))
        if photo is not None:
            px, py = int(photo_spec.get("x", PHOTO_BOX[0])), int(photo_spec.get("y", PHOTO_BOX[1]))
            pw, ph = int(photo_spec.get("width", PHOTO_BOX[2])), int(photo_spec.get("height", PHOTO_BOX[3]))
            fitted = fit_cover(photo, pw, ph)
            rounded = add_rounded_corners(fitted, radius=int(photo_spec.get("corner_radius", PHOTO_CORNER_RADIUS)))
            im.paste(rounded, (px, py), rounded)

    texts = layout.get("texts", {})

    name_spec = texts.get("student_name")
    if name_spec and name_spec.get("enabled", True):
        val = str(data.get("student_name", "") or "")
        if name_spec.get("uppercase"):
            val = val.upper()
        draw_text_box(draw, val, name_spec)

    section_spec = texts.get("section")
    if section_spec and section_spec.get("enabled", True):
        val = str(data.get("section", "") or "").strip()
        if val:
            draw_text_box(draw, section_spec.get("prefix", "") + val, section_spec)

    for key, spec in texts.items():
        if key in ("student_name", "section"):
            continue
        if spec.get("enabled", True) is False:
            continue
        val = str(data.get(key, "") or "")
        draw_text_box(draw, val, spec)

    return im